---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: browseport32003
spec:
  type: NodePort
  selector:
    app: appreaction #will be the name for the react app 
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 32003
    
---
apiVersion: v1
kind: Service
metadata:
  name: browseport32004
spec:
  type: NodePort
  selector:
    app: nginx #the name for its nginx app connected
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32004
